### ISSUE TITLE
Ocultar seta quando na primeira e última página

### ISSUE THREAD

**Issue by wilderamorim** [robsonvleite/paginator#2]
Quando estamos na primeira página é exibida uma setinha para voltar à página anterior mesmo não havendo. A mesma coisa na última página que é exibida uma seta para ir para a próxima.
Seria interessante fazer essa implementação para melhorar a usabilidade.

**Comment by robsonvleite** [comment]
> Quando estamos na primeira página é exibida uma setinha para voltar à página anterior mesmo não havendo. A mesma coisa na última página que é exibida uma seta para ir para a próxima.
> Seria interessante fazer essa implementação para melhorar a usabilidade.

Boa, feito meu velho. Exemplo adicionado no readme.
