### ISSUE TITLE
Erro na contrução dos parametros na queryString

### ISSUE THREAD

**Issue by minha-encomenda** [robsonvleite/paginator#8]
Para funcionar trocar o '&" para "?" no método addGetParams

private function addGetParams(array $params)
    {
        $this->params = '';
        
        if (count($params) > 0) {
			
            if (isset($params['page'])) {
                unset($params['page']);
            }
            
            $this->params  = '&';
            $this->params .= http_build_query($params);
        }
        
        return $this;
    }

**Comment by robsonvleite** [comment]
O primeiro parâmetro sempre será o page= @minha-encomenda, por isso o segundo entra como &.
